#!/bin/sh

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

FLAKE="m3"
SYSTEM="darwinConfigurations.$FLAKE.system"

echo "${YELLOW}Starting build...${NC}"
NIXPKGS_ALLOW_UNFREE=1 nix --experimental-features 'nix-command flakes' build .#$SYSTEM "$@"

echo "${YELLOW}Switching to new generation...${NC}"
./result/sw/bin/darwin-rebuild switch --flake .#$FLAKE "$@"

echo "${YELLOW}Cleaning up...${NC}"
unlink ./result

echo "${GREEN}Switch to new generation complete!${NC}"
