window:
  option_as_alt: Both
  # Blank space added around the window in pixels
  padding:
    x: 0
    y: 0

  # Spread additional padding evenly around the terminal content
  dynamic_padding: true
  decorations: full

font:
  normal:
    family: 'JetBrainsMono Nerd Font'
    style: Regular

  size: 16

# TokyoNight Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0x222436'
    foreground: '0xc8d3f5'

  # Normal colors
  normal:
    black: '0x1b1d2b'
    red: '0xff757f'
    green: '0xc3e88d'
    yellow: '0xffc777'
    blue: '0x82aaff'
    magenta: '0xc099ff'
    cyan: '0x86e1fc'
    white: '0x828bb8'

  # Bright colors
  bright:
    black: '0x444a73'
    red: '0xff757f'
    green: '0xc3e88d'
    yellow: '0xffc777'
    blue: '0x82aaff'
    magenta: '0xc099ff'
    cyan: '0x86e1fc'
    white: '0xc8d3f5'

  indexed_colors:
    - { index: 16, color: '0xff966c' }
    - { index: 17, color: '0xc53b53' }

shell:
  program: fish

cursor:
  style:
    shape: Beam
    blinking: Always
    blink_interval: 500
    unfocused_hollow: true
    thickness: 0.15
  vi_mode_style:
    shape: Block
