on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: full

jobs:
  DeterminateCI:
    uses: ./.github/workflows/ci.yml
    permissions:
      id-token: "write"
      contents: "read"
    with:
      enable-ssh-agent: true
    secrets:
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      cachix-name: genki
      cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      github-access-token: ${{ secrets.GITHUB_TOKEN }}
